# Generated by Django 5.0.3 on 2024-03-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('url', models.URLField()),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
