# Generated by Django 5.0.3 on 2024-03-31 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
        ('episode', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='episode',
            field=models.ManyToManyField(related_name='episode_number', to='episode.episode'),
        ),
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_characters', to='location.location'),
        ),
        migrations.AddField(
            model_name='character',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_characters', to='location.location'),
        ),
    ]
