# Generated by Django 5.0.3 on 2024-03-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
