# Generated by Django 5.0.3 on 2024-04-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_alter_character_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='created',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
