# Generated by Django 5.0.3 on 2024-03-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('dimension', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('created', models.DateTimeField()),
                ('residents', models.ManyToManyField(related_name='residing_locations', to='character.character')),
            ],
        ),
    ]
